### ISSUE TITLE
I see no files and my quota is zero

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#21]
Currently, at https://cernbox.test.up2university.eu/cernbox/, I see "No files in here", however I have had some files earlier. In fact, they are still accessible from SWAN but not from CERNBox. In addition, when I'm trying to upload anything to CERNBox, it says:
> Error uploading file "file.pdf": Not enough free space, you are uploading 32 KB but only 0 B is left

It's not the first time it happens. I suppose that restarting cernbox' pods would solve the issue. 

I'd like us, however, to track the cause.

When I'm refreshing my home directory page, something like [this](https://pastebin.com/VAseGMc2) appears multiple times in /var/log/httpd/error_log of the cernbox container.

Perhaps, same as for #19, Kubernetes readiness probes should be implemented for such cases to enable Kubernetes to react automatically (e.g. restart some pods).

**Comment by michzimny** [comment]
Please let me know if there are any other log files I can preserve for you before I restart the pods.

**Comment by michzimny** [comment]
Recreating first cernbox and then cernbox-gateway pods has solved the issue. 

But let's study please what was the cause and how to make kubernetes aware in the future.

**Comment by diocas** [comment]
We can study this problem, but CERNBox is in process of being upgraded with a major new version, so I don't know if this is relevant for now. I say this because the complete backend is being replaced.

**Comment by michzimny** [comment]
Ok, if the newer version is coming then it does not make sense to deeply study the old one.

@diocas, what is the timeline to have the upgraded version you mentioned in kuboxed?

**Comment by diocas** [comment]
We're trying to have until the end of this year.
We are making progresses in CERNBox, but then we need to test the OCM capabilities. Then we'll proceed to updating SWAN and trying to fix some of the issues registered here.

**Comment by ebocchi** [comment]
Hi @michzimny,
independently on update campaigns, the problem you saw was due to misconfigured permissions on the EOS side. In this respect, CERNBox and CERNBox Gateway are "golden boxes" from the EOS perspective. There was a missing entry on the EOS headnode, inhibiting CERNBox from having the right permission to access files and folders.

This permission issue happens from time to time and I suspect it is due to a sequence of events that goes like this:
- one of CERNBox pods fails and is restarted, getting a new IP address;
- when the pod starts, it self-registers on the eos-side as "golden box" according to its IP address;
- the same pod has also an headless-service resource in kubernetes, which allows to resolve (and reverse-resolve) "cernbox.svc.[...]" to the IP address of the pod;
- from that moment on, the CERNBox pod is identified via the headless-service, which does not have special permissions, EOS-side. There comes the permission denied issue.

This happened already in the past and a workaround was put in place.
In newer releases, 'cernbox.svc.[...]' is always set up as golden box, and the pod (upon starting) still registers itself using the IP address.


Cleaning up old permission settings and re-granting permission to CERNBox pod fixed the issue.
I also created the 'cernbox.svc.[...]' entry manually.

If it happens again, I will investigate more.
Maybe there is a corner case which is not covered yet.
