### ISSUE TITLE
User redirected to the standard login page in CERNBox

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#35]
A user reports his issue as follows:
* opening https://cernbox.test.up2university.eu/
* seeing the SSO page
* choosing Google and authenticating
* redirected to https://cernbox.test.up2university.eu/cernbox/index.php/login and seeing:
![Zrzut ekranu 2019-04-09 o 08 05 05](https://user-images.githubusercontent.com/1483196/55914352-323de180-5be7-11e9-9543-00c01fb3062c.png)

He reports it happens every time for him. I cannot reproduce. The user is rather advanced. What could we check more?

@diocas, the instance is not yet upgraded to the latest version that you mentioned in your today's email.

**Comment by diocas** [comment]
We had some similar problem before in that instance. Our internal ldap registry was missing some data, so CERNBox received the information that the user existed but when the information necessary was requested, the reply was empty. Is this a new user or was there in the system before?
If the user is new and has no content, reseting his data in ldap would work.

**Comment by michzimny** [comment]
I'm not sure. But I've tried with two brand new Google accounts and I authenticated successfully, so perhaps he's a returning user...?

**Comment by diocas** [comment]
This is related to corrupted data in ldap so please send me more details by email. I'll check directly in the server.

**Comment by michzimny** [comment]
Just sent via email.

**Comment by diocas** [comment]
Ldap had ssoAttributes created to him but was missing ssoUnixMatch, so I don't believe he had storage created before.
He can go ahead and try again. Let me know if this time it works.
I'll try to see in the logs if there's anything there

**Comment by diocas** [comment]
Hi Michal,


For future problems, to fix this issue, I did the following (from inside the CERNBox container):


$ ldapsearch -x -H $LDAP_URI -D $LDAP_BIND_DN -w $LDAP_BIND_PASSWORD -b $LDAP_BASE_DN "mail=email@address.com" -LLL


This should return 2 entries: ssoAttributes and ssoUnixMatch. He was missing ssoUnixMatch, so I just deleted the other one so that he can try again.


To delete:

$ ldapdelete -x -H $LDAP_URI -D $LDAP_BIND_DN -w $LDAP_BIND_PASSWORD ssouid=_THE_ID_OF_THE_USER_RETURNED_ON_SEARCH_,$LDAP_BASE_DN


I’ll try to see if I find the cause and if it can be avoided.


Cheers,

Diogo

**Comment by michzimny** [comment]
I have no feedback from the user. I'm closing for now.
