### ISSUE TITLE
Swan has HTTPS cert not properly configured

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#4]
Intermediate certs are not read by Apache.

My investigations explained in an email.

**Comment by ebocchi** [comment]
Fixed by adding directive "SSLCertificateChainFile /etc/boxed/certs/boxed.crt" in apache configuration.

The web server providing swan.test.up2university.eu runs on a temporary fix (which will be wiped out in case container restarts).
The fix is embedded in Docker image "gitlab-registry.cern.ch/cernbox/boxedhub/jupyterhub:v0.5"
