### ISSUE TITLE
SWAN - [Errno 28] No space left on device

### ISSUE THREAD

**Issue by gtoffoli** [up2university/kuboxed#41]
Trying to save changes to a notebook, I repeatedly got this error message:

![2019-07-18_114419](https://user-images.githubusercontent.com/983587/61447868-1c605b00-a952-11e9-822a-cd1b17549ab4.png)

Also, I had some trouble getting my SWAN session started and wasn't able to open another notebook.

I don't think I've exceeded my disk quota, since I didn't add files or load new libraries since a while.

**Comment by michzimny** [comment]
It should be fine now. It works for me. Please try again and report back.

Earlier today, we experienced physical damage in network connection between the machines behind Kuboxed services (incl. SWAN). After recovery, some components (EOS FST pods) have not been recreated because of issue #40. I manually brought them back to live.

**Comment by gtoffoli** [comment]
I confirm that everything seems to be fine now. Thank you!
