### ISSUE TITLE
SWAN daemons not deployed in Kubernetes cluster

### ISSUE THREAD

**Issue by ebocchi** [up2university/kuboxed#5]
For reasons to be investigated, swan daemons to access EOS and CVMFS are not deployed in the cernbox-alpha cluster.
I have already tried to:
- deploy the daemons and user sessions ("swan-user" label) on another cluster node;
- remove and re-add the node labeled with "swan-users" (cernbox-alpha-1) to the cluster;
- reinstall docker and kubernetes on cernbox-alpha-1;
- restart various services on cernbox-alpha-1;
- look into `/var/log/messages`;
- look into journalctl -u {kube*, docker*}
with no luck.

I think I will need help @michzimny to proceed on this as there might be some specificities about the cluster I am not aware of.

**Comment by michzimny** [comment]
@ebocchi, just a quick comment: the cluster is set up with the script https://github.com/michzimny/kuboxed/blob/master/InitNode.sh and https://github.com/michzimny/kuboxed/blob/master/etc/common.sh. The only change to your upstream is the Kubernetes version that has been bumped to 1.8.1.0 because of a bug in 1.8.0: https://github.com/kubernetes/kubernetes/issues/53288

After running the scripts the worker nodes have just joint the master and get labales. That's all.

I have the whole setup process expressed in an ansible playbook. Starting from the marked line you can extract shell commands invoked on master and workers respectively: https://gist.github.com/michzimny/74c05afd647e7e7d79dded6648a91915#file-up2u-kuboxed-cluster-yml-L27

I will study the issue further soon.

**Comment by ebocchi** [comment]
@michzimny 
This has already been fixed (see email thread)
Thanks a lot for your heads-up! I am now closing this one
